# H2 設定
spring.datasource.url=jdbc:h2:mem:factorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 コンソール
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL 初期化
spring.sql.init.mode=always

# ログ
logging.level.com.example=DEBUG
